#Global configuration
spring.application.name=SafetyNetAlerts

#Toncat configuration
server.port=8080

#Log level configuration
logging.level.root=ERROR
logging.level.com.SafetyNet.SafetyNetAlerts=DEBUG
logging.level.org.springframework.web=INFO
